version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: biblioteca
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
